Development
DarkShadow20/Ecommerce pull request #1
Opened 2021-04-02 14:39 UTC by DarkShadow20

2021-04-02 19:03 UTC, DanishOnGit commented on src/App.js
> +import Home from "./ProductList/Home";
Hi Kunal,
you can bundle all your exports of one folder in an index.js.
Then, ur import will look something like this:
import Header from "./ProductList"

2021-04-02 19:08 UTC, DanishOnGit commented on src/ProductList/Home.js
> +    return products;
```suggestion
    if (priceRange) {
    return products.filter((item) => item.price <= priceRange);
    }
    return products;
```
Just for better readability...I think Tanay sir mentioned this... please correct me if i am wrong.

2021-04-02 19:09 UTC, DanishOnGit commented on src/ProductList/Home.js
> +  };
```suggestion
  const getSortedData = (products, sortBy) => {
    if (sortBy === "LOW_TO_HIGH")
      {
      return products.sort((a, b) => a.price - b.price);
      }
    if (sortBy === "HIGH_TO_LOW")
     {
      return products.sort((a, b) => b.price - a.price);
      }
    return products;
  };
```
Same...better readability

2021-04-02 19:10 UTC, DanishOnGit commented on src/ProductList/Home.js
> +  );
You can destructure your state here

2021-04-02 19:15 UTC, DanishOnGit commented on src/ProductList/Home.js
> +          <p className="input_field_radio_left"><input type="radio" name="price" onClick={() => dispatch({ type: "HIGH_TO_LOW" })}/>high to low</p>
classnames can be better. Eg: input_low_to_high

2021-04-02 19:18 UTC, DanishOnGit commented on src/ProductList/Home.js
> +            <div className="card-collection-wrapper">
You have used undescore completely earlier in class names but here hyphens are used. This breaks consistency

2021-04-02 19:23 UTC, DanishOnGit commented on src/Wishlist/Wish.js
> +    const [{wis},dispatch]=useCart();
wis?

2021-04-02 19:28 UTC, DanishOnGit commented on src/Wishlist/WishList.js
> +                    fastDelivery={items.fastDelivery}/>
You can destructure your items here

2021-04-02 19:30 UTC, DanishOnGit commented on src/cart/Cart.js
> +            <div className="cart-left">
class name can be better

2021-04-02 19:31 UTC, DanishOnGit commented on src/cart/Cart.js
> +                        image={item.image}
Destructure if convenient.

2021-04-02 19:32 UTC, DanishOnGit commented on src/cart/CheckoutCart.js
> +    const [{h},dispatch]=useCart();
h?

2021-04-02 19:34 UTC, DanishOnGit commented on src/cart/CheckoutCart.js
> +      };
keep consistency in writing the dispatch...
dispatch({type:"xyz", id:id})

Suggestion: dispatch({type:"xyz",payload:id})

2021-04-02 19:36 UTC, DanishOnGit commented on src/cart/Subtotal.js
> +    let quantArr=cart.map(item=>item.quantity)
Use full variable names. Quantity instead of quant.

2021-04-02 19:40 UTC, DanishOnGit commented on src/cart/Subtotal.js
> +    let subTotalItems=quantArr.reduce(reducer)
Its good to give reduce an initial value or you should handle the errors well. (Correct me if i am mistaken)

2021-04-02 19:56 UTC, DanishOnGit commented on src/context/reducer.js
> +            case "ADD_TO_CART_WISHLIST":
You can rename the case to "MOVE_TO_CART"

2021-04-02 19:57 UTC, DanishOnGit commented on src/context/reducer.js
> +                if(fromExisted_item)
You can rename the case to "MOVE_TO_CART".
Also,can we use const instead of let ?

2021-04-02 19:59 UTC, DanishOnGit commented on src/css/Header.css
> +    color: #fff;
use color variables here

2021-04-02 20:04 UTC, DanishOnGit commented on src/ProductList/Header.js
> +                <h1 className="header__logo">Nile</h1>
Avoid inline style as much as possible

2021-04-02 20:06 UTC, DanishOnGit commented on src/css/ProductList.css
> +}
use color variables

2021-04-02 20:07 UTC, DanishOnGit commented on src/css/ProductList.css
> +    max-height: 200px;
use rem units as far as possible

2021-04-02 20:07 UTC, DanishOnGit commented on src/css/ProductList.css
> +    border: 1px solid #a88734;
use color variables

2021-04-02 20:07 UTC, DanishOnGit commented on src/css/Subtotal.css
> +    border: 1px solid #dddddd;
color var here too

2021-04-02 20:11 UTC, DanishOnGit reviewed
Hi Kunal,
I have suggested around destructuring, using full variable names , css variables and consistency in code

2021-04-03 05:23 UTC, DarkShadow20 commented
Hey, @DanishOnGit made some changes suggested by you.

2021-04-03 06:01 UTC, iamrishavb reviewed
Hey @DarkShadow20 code it well written. Suggested some changes, and you should use normal CSS naming convention because i think you component library is in that using different naming conventions will be inconsistent.

2021-04-03 06:01 UTC, 0xRishav commented on public/manifest.json
> +}
Hi Kunal, 
You should edit manifest file this helps in SEO

2021-04-03 06:01 UTC, 0xRishav commented on src/App.js
> +import Home from "./ProductList/Home";
As Danish commented,
make an index.js file in components folder
ex for header:
export { default as Header } from "./ProductList/Header";
you can export each component from index.js like this and import directly from index.js

2021-04-03 06:01 UTC, 0xRishav commented on src/App.js
> +    </Router>
You should add exact = true in each route for exact routing (= true is not required you can just put exact it will work).

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/Home.js
> +  };
You can use spread operator here {...state} then use state then use keys directly

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/Home.js
> +  const sortedData = getSortedData(priceRangeData, state.sortBy);
destructuring state before would be better

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/Home.js
> +    {state}
here also you can do {...state}

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/Home.js
> +                    fastDelivery={items.fastDelivery}
you can just put {...items} rather than writing it individually it will work the same

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/ProductList.js
> +    }
you can directly dispatch from onClick no need to create individual functions.

2021-04-03 06:01 UTC, 0xRishav commented on src/ProductList/ProductList.js
> +        <div class="card-collection-wrapper">
You should only use one naming convention either use BEM or use normal using both is not good practice.

2021-04-03 06:01 UTC, 0xRishav commented on src/Wishlist/Wish.js
> +    console.log(wishlist)
remove console logs every time after debugging.

2021-04-03 06:01 UTC, 0xRishav commented on src/Wishlist/Wish.js
> +    }
same dispatch directly from click action

2021-04-03 06:01 UTC, 0xRishav commented on src/Wishlist/Wish.js
> +        // </div>
You can remove this code if it is not useful

2021-04-03 06:01 UTC, 0xRishav commented on src/Wishlist/WishList.js
> +                    fastDelivery={items.fastDelivery}/>
here also just put {...items}

2021-04-03 06:01 UTC, 0xRishav commented on src/cart/CheckoutCart.js
> +    console.log({state})
remove console log

2021-04-03 06:01 UTC, 0xRishav commented on src/cart/CheckoutCart.js
> +      };
dispatch directly from click action

2021-04-06 12:57 UTC, Rupamdas832 requested changes
Hey Kunal, very well written code. I have suggested some good practices. Hope it helps.
Some suggestions on UI are:
1. Show something on the Add to Cart button, when the item is added to cart. Like ADDED or Go to Cart.
2. Cart items can be in list format. Like Horizontal card.
3. Out of stock items are hard to distinguish among others (as you have used strikethrough styling for it). See some refrences.
4. Add reset button for sorting and filters.

2021-04-06 12:57 UTC, Rupamdas832 commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
Add your own logo here

2021-04-06 12:57 UTC, Rupamdas832 commented on public/index.html
> +    <title>React App</title>
Remove React App and add your own app title

2021-04-06 12:57 UTC, Rupamdas832 commented on src/App.js
> +            <Header/>
If Header component is in every route, then move it out from switch case and put it above switch case.

2021-04-06 12:57 UTC, Rupamdas832 commented on src/Cart.js
> +    console.log(cart)
Remember to remove all the console.log from your code

2021-04-06 12:57 UTC, Rupamdas832 commented on src/Cart.js
> +                    {cart.map(item=>(
Destructure the item(as everyone suggested)

2021-04-06 12:57 UTC, Rupamdas832 commented on src/ProductList.js
> +        dispatch({
It is a good practice to write   dispatch({ type: "SOMETING", payload: item })  in this format always

2021-05-05 16:26 UTC, merged